### ISSUE TITLE
Tests and linting through Travis CI

### ISSUE THREAD

**Issue by ziir** [CaliOpen/caliopen.web#5]
At the moment:
- tests and linting are not run through a CI.
- tests are too few.
- there are multiple linting errors if you run `npm run eslint`

I suggest we use Travis CI to run tests and linting, in order to ease contribution and code quality.

@KillianKemps Would you like to work on this? 
Of course, I'm available to give you a hand if needed - not that I think you need help of any kind :)

**Comment by KillianKemps** [comment]
Yes, I will work on setting up a Travis CI job for the repository. I've created the related Trello card https://trello.com/c/w5jjEs0Q/51-caliopen-web-set-up-travis-ci-for-tests-and-linting
Thank you for your help, I will see if I will need it.
